language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
allow_failures:
  - php: hhvm
  - php: 7.0
  - php: 5.3

install:
  - composer install

script: phpunit --configuration phpunit.xml --coverage-text
